#!/bin/bash

function run {
  echo "Not implemented yet"
}

function stop {
  echo "Not implemented yet"
}

function clean {
  echo "Not implemented yet"
}

function main {
  if [[ $1 =~ ^(help|clean|run|stop|clean-run)$ ]]; then
    case $1 in
      help)
        echo "Usage:"
        echo "    help  - Prints this info"
        echo "    clean - Stops and deletes the locally created Jenkins containers"
        echo "    stop  - Stops the running Jenkins containers"
        echo "    run   - Runs the data volume and Jenkins service"
        echo "    clean-run - Stops, deletes, recreates and runs the Jenkins service and data volume"
        echo
      ;;
      clean)
        clean
      ;;
      run)
        run
      ;;
      stop)
        stop
      ;;
      clean-run)
        clean && run
      ;;
      *)
      ;;
    esac
  else
    echo "Invalid subcommand $1" >&2
    exit 1
  fi
}

main $1
